BITRIX_ACTION_EQUIPPED = 'equipped'
BITRIX_ACTION_DELIVERY = 'delivery'
BITRIX_ACTION_WAITING_FOR_SUPPLY = 'waiting_for_supply'
BITRIX_ACTION_RESERVED = 'reserved'
BITRIX_ACTION_UNAPPROVED = 'unapproved'

DEAL_IS_RESERVED_YES = 'Да'
DEAL_IS_RESERVED_NO = 'Нет'

# equipped approvement
EQUIPPED_APPROVEMENT_OK = '3463'  # Согласовано
EQUIPPED_APPROVEMENT_REJECT = '3465'  # Не согласовано

